#!/usr/bin/python
#
# run all tests
#

import os
import sys
import signal
import time
import subprocess


def signal_handler(signal,frame):
  print "bye\n"
  sys.exit(0)
signal.signal(signal.SIGINT,signal_handler)

def shellGetOutput(str) :
  process = subprocess.Popen(str,shell=True,stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE)
  output, err = process.communicate()
  
  if (len(err) > 0):
      raise NameError(str+"\n"+output+err)
  return output

#applications = ["levelWTOpt","levelWTOpt2","sortWTOpt","sortWTOpt2","msortWT","msortWT2", "levelWTOptLight", "levelWTRec", "ddWt" ]
#serial_applications=["serialWT","serialWT2"]
applications = ["select", "rank"]
serial_applications=["selectSerial", "rankSerial"]

#testfiles = ["chr22.dna","etext99","howto","jdk13c","rctail96","rfc","sprot34","w3c2","wikisamp.xml"]

testfiles = ["sources", "pitches", "proteins", "dna", "english", "dblp.xml"]

processors = [1,2,4]+range(8,80+1,8)
#processors = range(40,81,8)

for testfile in testfiles :
  for app in applications:
    for p in processors : #parallel
      if p == 1:
        os.system("unset GCILK; cd "+app+"; make clean -s; make -s; cd ..");
        ss = "./" + app + "/WT -r 5 ~/testdataBig/"+testfile
        print app+" 1 " + testfile
        print shellGetOutput(ss)
        sys.stdout.flush()
        os.system("export GCILK=1; cd "+app+"; make clean -s; make -s; cd ..");
      else:
        ss = "CILK_NWORKERS="+`p`+" numactl -i all ./" + app + "/WT -r 5  ~/testdataBig/"+testfile
        print app+" "+`p` + " " + testfile
        print shellGetOutput(ss)
        sys.stdout.flush()

  for app in serial_applications:
    os.system("cd "+app+"; make -s; cd ..");
    ss = "./" + app + "/WT -r 5  ~/testdataBig/"+testfile
    print app + " " + testfile
    print shellGetOutput(ss)
    sys.stdout.flush()

