#!/usr/bin/python

bnchmrk="WT"
benchmark="Wavelet Tree"
checkProgram="../common/WTCheck"
dataDir = "../sequenceData/data"

tests = [
    [1, "trigramString_10000000", "", ""],
    [1, "chr22.dna", "", ""],
    [1, "etext99", "", ""],
    #[1, "HG18", "", ""],
    [1, "howto", "", ""],
    [1, "jdk13c", "", ""],
    [1, "proteins", "", ""],
    [1, "rctail96", "", ""],
    [1, "rfc", "", ""],
    [1, "sprot34", "", ""],
    [1, "w3c2", "", ""],
    [1, "wikisamp.xml", "", ""],
    [1, "randomSeq_100M_256_int", "", ""],
    [1, "randomSeq_10M_100K_int", "", ""],
    [1, "randomSeq_10M_1048576_int", "", ""],
    [1, "randomSeq_10M_256_int", "", ""],
    [1, "wikisamp.xml", "", ""],
]

import runTests
runTests.timeAllArgs(bnchmrk, benchmark, checkProgram, dataDir, tests)

